apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  ports:
    - port: 2551
      protocol: TCP
      targetPort: 2551
  selector:
    run: node-01
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: node-01
  name: node-01
spec:
  serviceName: client-service
  replicas: 1
  selector:
    matchLabels:
      run: node-01
  template:
    metadata:
      labels:
        run: node-01
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: node01
          image: akka-in-k8s:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SEED_NODES
              value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          command: ["/bin/sh", "-c", "HOSTNAME=${POD_NAME}.client-service sbt run"]
          ports:
            - containerPort: 2551
              protocol: TCP
