apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: akka-worker
  name: akka-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      run: akka-worker
  template:
    metadata:
      labels:
        run: akka-worker
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: akka-worker
          image: akka-in-k8s:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SEED_NODES
              value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          command: ["/bin/sh", "-c", "sbt run"]
          ports:
            - containerPort: 2551
              protocol: TCP